### ISSUE TITLE
Only 412*548 dimension image expected during evaluation

### ISSUE THREAD

**Issue by abdullahahsann** [sanchitvj/Image-Dehazing-using-GMAN-net#1]
Hey!
I hope you are well.
There's one issue that i face.
When using the model for evaluation, it doesn't accept any image other then an image of dimensions 412*548, cause that's the input shape defined in the model. 
So i have to change the evaluation function to have it resize to  412*548 (which distorts the images), while you yourself are using an 1920*1080 image resize, which did worked for you.
Can you guide me anyhow on how to resolve this.
Thankyou :) 

![Screenshot from 2021-05-18 07-56-05](https://user-images.githubusercontent.com/62840383/118585567-9cf07c80-b7b2-11eb-9526-52893be926c9.png)

**Comment by sanchitvj** [comment]
Ok I'll take a look at this issue and get back to you.

**Comment by abdullahahsann** [comment]
Thanks a lot.
I'll really appreciate it.
I did got around it by storing the original dimensions of an image in a temp, converting the image to 412 X 518, passing it through the model, and then resizing the image and dehazed_image back to their original size.
But there could be a better way probably.
Let me know for sure :) .
